dialect = "uk"
update_check = false
sync_address = "https://shellhist.hess.nz"
filter_mode = "host"
workspaces = false # not yet: https://github.com/atuinsh/atuin/pull/1417
keymap_mode = "vim-insert"
show_help = false
ctrl_n_shortcuts = true
enter_accept = false
