#!/usr/bin/env bash

# This script installs all Firefox addons

. @DOTFILES@/graphical/firefox/addons
data="$(@DOTFILES@/scripts/ff-profile)"

if ! [ -d "${data}/extensions" ]; then
	mkdir -pv "${data}/extensions"
fi

changed=0
# Look for missing addons
for addon in "${addons[@]}"; do
	name="$(echo "${addon}" | cut -d':' -f1)"
	id="$(echo "${addon}" | cut -d':' -f2)"
	download="$(echo "${addon}" | cut -d':' -f3-)"
	# Check if already there
	if ! [ -f "${data}/extensions/${id}.xpi" ]; then
		# Install
		echo "Installing ${name}"
		curl -sLo "${data}/extensions/${id}.xpi" "${download}"
		changed=1
	fi
done

if [ "${changed}" = 1 ]; then
	echo
	echo Please restart Firefox and enable all Addons
	echo
fi
