#!/usr/bin/env bash

set -euo pipefail

if [[ "${1}" == 'Confirm user presence'* ]]; then
	read -r -a parts <<< "${1}"
	key="${parts[*]: -2:2}"
	dunstify -a ssh --printid 'Confirm user presence for key' "${key}"
	exit
fi

askpass="$(. /etc/set-environment; echo "${SSH_ASKPASS}")"
exec "${askpass}" "${@}"
