#!/usr/bin/env bash

set -euo pipefail

focusedWorkspace="$(hyprctl activeworkspace -j | jq .id)"
readarray -t monitors <<< "$(hyprctl monitors -j | jq -r '.[] | select(.name != "eDP-1") | "\(.id)"')"

if [[ "${#monitors[@]}" != 2 ]]; then
	echo "Not exactly 2 displays" >&2
	exit 1
fi

hyprctl dispatch swapactiveworkspaces "${monitors[@]}"
hyprctl dispatch workspace "${focusedWorkspace}"
