#!/usr/bin/env bash

killAndWait() {
	pkill "${1}"
	while pgrep "${1}"; do sleep .1; done
}

killStuff() {
	killAndWait firefox &
	wait
}

out="$(echo 'Log Out
Shut down
Suspend
Reboot
Hibernate
Kexec
Hybrid sleep' | rofi -dmenu -p 'power')"

[ -z "${out}" ] && exit

case "${out}" in
	'Log Out')
		killStuff
		i3-msg exit
	;;
	'Shut down')
		killStuff
		systemctl poweroff
	;;
	'Suspend')
		systemctl suspend
	;;
	'Hibernate')
		systemctl hibernate
	;;
	'Hybrid sleep')
		systemctl hybrid-sleep
	;;
	'Reboot')
		killStuff
		systemctl reboot
	;;
	'Kexec')
		killStuff
		systemctl kexec
	;;
esac
