#!/usr/bin/env sh

out="$(echo 'Select Area/Window
Current Screen
All Screens
Select Area/Window (3s)
Current Screen (3s)
All Screens (3s)' | rofi -dmenu -p '> ')"

# Cancel
[ -z "${out}" ] && exit

# Sleep
s=0
case "${out}" in
	*'(3s)')
		s=3
		;;
esac

# Maim parameters
params=''
case "${out}" in
	'Select Area'*)
		params='-s'
		;;
	'Current Window'*)
		params="-i $(xdotool getactivewindow)"
		;;
	'Current Screen'*)
		params=''
		monitors="$(xrandr | grep -o '[0-9]*x[0-9]*[+-][0-9]*[+-][0-9]*')"
		mouseX="$(xdotool getmouselocation | awk -F "[: ]" '{print $2}')"
		mouseY="$(xdotool getmouselocation | awk -F "[: ]" '{print $4}')"
		for mon in ${monitors}; do
			# Monitor geometry
			monWidth="$(echo "${mon}" | awk -F "[x+]" '{print $1}')"
			monHeight="$(echo "${mon}" | awk -F "[x+]" '{print $2}')"
			monX="$(echo "${mon}" | awk -F "[x+]" '{print $3}')"
			monY="$(echo "${mon}" | awk -F "[x+]" '{print $4}')"
			# Collision check
			if (( ${mouseX} >= ${monX} )) && \
				(( ${mouseX} <= ${monX}+${monWidth} )) && \
				(( ${mouseY} >= ${monY} )) && \
				(( ${mouseY} <= ${monY}+${monHeight} )); then
				params=("-g" "${monWidth}x${monHeight}+${monX}+${monY}")
			fi
		done
		;;
	'All Screens'*)
		params=''
		;;
esac

maim -q -u -d "${s}" "${params[@]}" | xclip -selection clipboard -t image/png
if [ "${s}" != 0 ]; then
	dunstify -a maim 'Screenshot taken' 'and copied to clipboard'
fi
