#!/usr/bin/env bash
set -euo pipefail

killAndWait() {
	pkill "${1}"
	while pgrep "${1}"; do sleep .1; done
}

killStuff() {
	killAndWait firefox &
	wait
}

launcher() {
	if [[ "${XDG_SESSION_TYPE:-}" = wayland ]]; then
		fuzzel --dmenu -p 'power> '
	else
		rofi -dmenu -p power
	fi
}

out="$(echo 'Log Out
Shut down
Suspend
Reboot
Hibernate
Kexec
Hybrid sleep
Windows' | launcher)"

[[ -z "${out}" ]] && exit

case "${out}" in
	'Log Out')
		killStuff
		if [[ "${XDG_SESSION_TYPE:-}" = wayland ]]; then
			uwsm stop
		else
			i3-msg exit
		fi
	;;
	'Shut down')
		killStuff
		systemctl poweroff
	;;
	'Suspend')
		systemctl suspend-then-hibernate
	;;
	'Hibernate')
		systemctl hibernate
	;;
	'Hybrid sleep')
		systemctl hybrid-sleep
	;;
	'Reboot')
		killStuff
		systemctl reboot
	;;
	'Kexec')
		killStuff
		systemctl kexec
	;;
	'Windows')
		killStuff
		sudo /run/current-system/sw/bin/bootctl set-oneshot auto-windows
		systemctl reboot
esac
