#!/usr/bin/env sh
set -e
dotfiles="$(dirname "$(dirname "$(readlink -f "${0}")")")"

if [ "$(basename "${1}")" = 'clean-filter' ] || [ "$(basename "${1}")" = 'smudge-filter' ]; then
	exec cat
fi

sed "s:@DOTFILES@:$dotfiles:g" | \
	sed "s:@HOME@:$HOME:g"
