#!/usr/bin/env sh

# Simplified version of startx.
# Responsible for starting a proper X session

unset SESSION_MANAGER
set -o nounset
set -e

# Determine an unsused $DISPLAY
display=0
while :; do
	[ -e "/tmp/.X${display}-lock" ] || break
	display=$((display + 1))
done
display=":${display}"

# When starting the default server start X on the current tty to avoid
# the startx session being seen as inactive:
tty="$(tty)"
if expr match "${tty}" '^/dev/tty[0-9]\+$' > /dev/null; then
	vtarg="vt$(echo "${tty}" | grep -oE '[0-9]+$')"
else
	exit 77
fi

# Set up Xauth
hostname="$(hostname)"
mcookie="$(mcookie)"
XAUTHORITY="$(mktemp -p /tmp serverauth.XXXXXXXXXX)"
dummy=0
trap 'rm -f "${XAUTHORITY}"' HUP INT QUIT ILL TRAP BUS TERM
xauth -q -f "${XAUTHORITY}" << EOF
add :${dummy} . ${mcookie}
EOF

# Add the same credentials to the client authority file
removelist=
for displayname in "${display}" "${hostname}/unix${display}"; do
	cookie="$(xauth list "${displayname}" |\
		sed -n "s/.*${hostname}\/unix${display}[[:space:]*].*[[:space:]*]//p")" 2>/dev/null;
	if [ -z "${cookie}" ]; then
		xauth -q <<EOF
add ${displayname} . ${mcookie}
EOF
		removelist="${displayname} ${removelist}"
	else
		dummy=$((dummy + 1))
		xauth -q -f "${XAUTHORITY}" <<EOF
add :${dummy} . ${cookie}
EOF
	fi
done

# Run X
export XAUTHORITY
xinit @DOTFILES@/graphical/xinitrc -- "$(command -v X)" "${display}" "${vtarg}" -auth "${XAUTHORITY}"
retval="${?}"

if [ -n "${removelist}" ]; then
	xauth remove "${removelist}"
fi
rm -f "${XAUTHORITY}"

if hash deallocvt >/dev/null 2>&1; then
	deallocvt
fi
exit "${retval}"
