#!/usr/bin/env sh

if hash xset >/dev/null 2>&1; then
	# No screen blanking
	xset s 0 0
	if [ -f '@DOTFILES@/local/dpms' ]; then
		xset dpms $(< '@DOTFILES@/local/dpms')
	else
		# Disable DPMS
		xset dpms 0 0 0
	fi
fi
