#!/bin/bash

if [ -f /usr/bin/xset ]; then
	# No screen blanking
	xset s 0 0
	if [ -f '@DOTFILES@/local/dpms' ]; then
		xset dpms $(< '@DOTFILES@/local/dpms')
	else
		# Disable DPMS
		xset dpms 0 0
	fi
fi
