#!/bin/sh

# Start dbus
if [ -z "${DBUS_SESSION_BUS_ADDRESS}" ]; then
	exec dbus-launch --exit-with-session "${0}"
fi

hash numlockx >/dev/null 2>&1 && numlockx &
hash nm-applet >/dev/null 2>&1 && nm-applet &
hash xcalib >/dev/null 2>&1 && @DOTFILES@/scripts/icc-profile &
hash xss-lock >/dev/null 2>&1 && xss-lock -- @DOTFILES@/scripts/i3-lock &
hash picom >/dev/null 2>&1 && picom &
xmodmap @DOTFILES@/graphical/Xmodmap &
setxkbmap -option compose:menu
@DOTFILES@/scripts/xset
# Import environment into systemd and dbus
dbus-update-activation-environment --systemd

# Start admin-defined programs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "${f}" ] && . "${f}"
	done
	unset f
fi

# Start user-defined programs
while IFS='' read -r f; do
	(gtk-launch "${f}" || :) &
done <<<"$(find .config/autostart -type f -name '*.desktop' -printf '%f\n')"

# Start window manager
exec i3
