#!/bin/sh

[ -x /usr/bin/numlockx ] && /usr/bin/numlockx &
xmodmap @DOTFILES@/graphical/Xmodmap &
# Screen blanking
if [ -f /usr/bin/xset ]; then
	if -f [ '@DOTFILES@/local/dpms' ]; then
		xset dpms "$(cat '@DOTFILES@/local/dpms')"
	else
		xset dpms 0 0 0
	fi
fi

# Start admin-defined programs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "${f}" ] && . "${f}"
	done
	unset f
fi

# Start user-defined programs
while IFS='' read -r f; do
	(gtk-launch "${f}" || :) &
done <<<"$(find .config/autostart -type f -name '*.desktop' -printf '%f\n')"

# Start window manager
exec /usr/bin/i3
