#!/bin/sh

hash numlockx >/dev/null 2>&1 && numlockx &
xmodmap @DOTFILES@/graphical/Xmodmap &
@DOTFILES@/scripts/xset
# Import environment into systemd
systemctl --user import-environment DISPLAY XAUTHORITY
dbus-update-action-environment

# Start admin-defined programs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "${f}" ] && . "${f}"
	done
	unset f
fi

# Start user-defined programs
while IFS='' read -r f; do
	(gtk-launch "${f}" || :) &
done <<<"$(find .config/autostart -type f -name '*.desktop' -printf '%f\n')"

# Start window manager
exec i3
